PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild: {}
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: activiti7-eks.youbpm.com
    exposer: Ingress
    http: "true"
    tlsacme: "false"
global:
  gateway:
    annotations:
      certmanager.k8s.io/issuer: letsencrypt-prod
    domain: activiti7-eks.youbpm.com
    host: activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}
    http: false
  keycloak:
    client: activiti
    host: ""
    realm: activiti
    resource: activiti
    url: ""
jenkins:
  Servers:
    Global: {}
prow: {}
